apiVersion: apps/v1
kind: Deployment
metadata:
  name: tienda-backend
  namespace: tienda
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tienda-backend
  template:
    metadata:
      labels:
        app: tienda-backend
    spec:
      containers:
      - name: backend
        image: 381492165352.dkr.ecr.us-east-1.amazonaws.com/tienda-perritos-backend:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: tienda-backend
  namespace: tienda
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: tienda-backend